<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Content_v3.proto

namespace GPBMetadata;

class ContentV3
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\DocumentId::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa2010a10436f6e74656e745f76332e70726f746f120c446961646f632e" .
            "50726f746f22780a0a436f6e74656e745f7633120f0a07436f6e74656e74" .
            "18012001280c12130a0b4e616d654f6e5368656c66180220012809122a0a" .
            "08456e74697479496418032001280b32182e446961646f632e50726f746f" .
            "2e446f63756d656e74496412180a1050617463686564436f6e74656e7449" .
            "64180420012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

