<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DssSignRequest.proto

namespace GPBMetadata;

class DssSignRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ContentV3::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab4010a144473735369676e526571756573742e70726f746f120c446961" .
            "646f632e50726f746f223a0a0e4473735369676e5265717565737412280a" .
            "0546696c657318012003280b32192e446961646f632e50726f746f2e4473" .
            "735369676e46696c65224a0a0b4473735369676e46696c6512290a07436f" .
            "6e74656e7418012001280b32182e446961646f632e50726f746f2e436f6e" .
            "74656e745f763312100a0846696c654e616d65180220012809620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

