<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RoamingOperatorInformation.proto

namespace GPBMetadata;

class RoamingOperatorInformation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab8020a20526f616d696e674f70657261746f72496e666f726d6174696f" .
            "6e2e70726f746f120c446961646f632e50726f746f22550a1a526f616d69" .
            "6e674f70657261746f72496e666f726d6174696f6e12370a10526f616d69" .
            "6e674f70657261746f727318012003280b321d2e446961646f632e50726f" .
            "746f2e526f616d696e674f70657261746f7222710a0f526f616d696e674f" .
            "70657261746f72120d0a05466e734964180120012809120c0a044e616d65" .
            "18022001280912100a084973416374697665180320012808122f0a084665" .
            "61747572657318042003280b321d2e446961646f632e50726f746f2e4f70" .
            "657261746f724665617475726522340a0f4f70657261746f724665617475" .
            "7265120c0a044e616d6518012001280912130a0b4465736372697074696f" .
            "6e180220012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

