<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DocumentType.proto

namespace Diadoc\Proto;

/**
 * Protobuf type <code>Diadoc.Proto.DocumentType</code>
 */
class DocumentType
{
    /**
     * Generated from protobuf enum <code>Nonformalized = 0;</code>
     */
    const Nonformalized = 0;
    /**
     * reserved for backward compatibility
     *
     * Generated from protobuf enum <code>UnknownDocumentType = -1;</code>
     */
    const UnknownDocumentType = -1;
    /**
     * Generated from protobuf enum <code>Invoice = 1;</code>
     */
    const Invoice = 1;
    /**
     * Generated from protobuf enum <code>TrustConnectionRequest = 11;</code>
     */
    const TrustConnectionRequest = 11;
    /**
     * Generated from protobuf enum <code>Torg12 = 12;</code>
     */
    const Torg12 = 12;
    /**
     * Generated from protobuf enum <code>InvoiceRevision = 13;</code>
     */
    const InvoiceRevision = 13;
    /**
     * Generated from protobuf enum <code>InvoiceCorrection = 14;</code>
     */
    const InvoiceCorrection = 14;
    /**
     * Generated from protobuf enum <code>InvoiceCorrectionRevision = 15;</code>
     */
    const InvoiceCorrectionRevision = 15;
    /**
     * Generated from protobuf enum <code>AcceptanceCertificate = 16;</code>
     */
    const AcceptanceCertificate = 16;
    /**
     * Generated from protobuf enum <code>ProformaInvoice = 18;</code>
     */
    const ProformaInvoice = 18;
    /**
     * Generated from protobuf enum <code>XmlTorg12 = 19;</code>
     */
    const XmlTorg12 = 19;
    /**
     * Generated from protobuf enum <code>XmlAcceptanceCertificate = 20;</code>
     */
    const XmlAcceptanceCertificate = 20;
    /**
     * Generated from protobuf enum <code>PriceList = 26;</code>
     */
    const PriceList = 26;
    /**
     * Generated from protobuf enum <code>PriceListAgreement = 30;</code>
     */
    const PriceListAgreement = 30;
    /**
     * Generated from protobuf enum <code>CertificateRegistry = 34;</code>
     */
    const CertificateRegistry = 34;
    /**
     * Generated from protobuf enum <code>ReconciliationAct = 35;</code>
     */
    const ReconciliationAct = 35;
    /**
     * Generated from protobuf enum <code>Contract = 36;</code>
     */
    const Contract = 36;
    /**
     * Generated from protobuf enum <code>Torg13 = 37;</code>
     */
    const Torg13 = 37;
    /**
     * Generated from protobuf enum <code>ServiceDetails = 38;</code>
     */
    const ServiceDetails = 38;
    /**
     * Generated from protobuf enum <code>SupplementaryAgreement = 40;</code>
     */
    const SupplementaryAgreement = 40;
    /**
     * Generated from protobuf enum <code>UniversalTransferDocument = 41;</code>
     */
    const UniversalTransferDocument = 41;
    /**
     * Generated from protobuf enum <code>UniversalTransferDocumentRevision = 42;</code>
     */
    const UniversalTransferDocumentRevision = 42;
    /**
     * Generated from protobuf enum <code>UniversalCorrectionDocument = 43;</code>
     */
    const UniversalCorrectionDocument = 43;
    /**
     * Generated from protobuf enum <code>UniversalCorrectionDocumentRevision = 44;</code>
     */
    const UniversalCorrectionDocumentRevision = 44;
    /**
     * Generated from protobuf enum <code>StorageInventoryAcceptanceCertificate = 45;</code>
     */
    const StorageInventoryAcceptanceCertificate = 45;
    /**
     * Generated from protobuf enum <code>ReturnInventoryAcceptanceCertificate = 46;</code>
     */
    const ReturnInventoryAcceptanceCertificate = 46;
    /**
     * Generated from protobuf enum <code>Torg2 = 47;</code>
     */
    const Torg2 = 47;
    /**
     * Generated from protobuf enum <code>ElectricityIndication = 48;</code>
     */
    const ElectricityIndication = 48;
    /**
     * Generated from protobuf enum <code>Waybill = 49;</code>
     */
    const Waybill = 49;
    /**
     * Generated from protobuf enum <code>PowerOfAttorney = 50;</code>
     */
    const PowerOfAttorney = 50;
    /**
     * Generated from protobuf enum <code>LogisticsWaybill = 51;</code>
     */
    const LogisticsWaybill = 51;
}

