<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DssSignResult.proto

namespace Diadoc\Proto;

/**
 * Protobuf type <code>Diadoc.Proto.DssConfirmType</code>
 */
class DssConfirmType
{
    /**
     * Generated from protobuf enum <code>None = 0;</code>
     */
    const None = 0;
    /**
     * Generated from protobuf enum <code>ComfirmTypeUnknown = -1;</code>
     */
    const ComfirmTypeUnknown = -1;
    /**
     * Generated from protobuf enum <code>Sms = 1;</code>
     */
    const Sms = 1;
    /**
     * Generated from protobuf enum <code>MyDss = 2;</code>
     */
    const MyDss = 2;
    /**
     * Generated from protobuf enum <code>Applet = 3;</code>
     */
    const Applet = 3;
    /**
     * Generated from protobuf enum <code>MobileSdk = 4;</code>
     */
    const MobileSdk = 4;
}

