<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DssSignResult.proto

namespace Diadoc\Proto;

/**
 * Protobuf type <code>Diadoc.Proto.DssFileSigningStatus</code>
 */
class DssFileSigningStatus
{
    /**
     * Generated from protobuf enum <code>UnknownSigningStatus = 0;</code>
     */
    const UnknownSigningStatus = 0;
    /**
     * Generated from protobuf enum <code>SigningCompleted = 1;</code>
     */
    const SigningCompleted = 1;
    /**
     * Generated from protobuf enum <code>SigningError = 2;</code>
     */
    const SigningError = 2;
}

