<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DssSignResult.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.DssFileSigningResult</code>
 */
class DssFileSigningResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DssFileSigningStatus FileSigningStatus = 1;</code>
     */
    private $FileSigningStatus = 0;
    /**
     * Generated from protobuf field <code>bytes Signature = 2;</code>
     */
    private $Signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $FileSigningStatus
     *     @type string $Signature
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DssSignResult::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DssFileSigningStatus FileSigningStatus = 1;</code>
     * @return int
     */
    public function getFileSigningStatus()
    {
        return $this->FileSigningStatus;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DssFileSigningStatus FileSigningStatus = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFileSigningStatus($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\DssFileSigningStatus::class);
        $this->FileSigningStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Signature = 2;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->Signature;
    }

    /**
     * Generated from protobuf field <code>bytes Signature = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->Signature = $var;

        return $this;
    }

}

