<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DssSignResult.proto

namespace Diadoc\Proto;

/**
 * Protobuf type <code>Diadoc.Proto.DssOperationStatus</code>
 */
class DssOperationStatus
{
    /**
     * Generated from protobuf enum <code>Unknown = 0;</code>
     */
    const Unknown = 0;
    /**
     * Generated from protobuf enum <code>InProgress = 1;</code>
     */
    const InProgress = 1;
    /**
     * Generated from protobuf enum <code>Completed = 2;</code>
     */
    const Completed = 2;
    /**
     * Generated from protobuf enum <code>CanceledByUser = 3;</code>
     */
    const CanceledByUser = 3;
    /**
     * Generated from protobuf enum <code>Timeout = 4;</code>
     */
    const Timeout = 4;
    /**
     * Generated from protobuf enum <code>Crashed = 5;</code>
     */
    const Crashed = 5;
    /**
     * Generated from protobuf enum <code>UserHasUnconfirmedOperation = 6;</code>
     */
    const UserHasUnconfirmedOperation = 6;
    /**
     * Generated from protobuf enum <code>OperationRetryRequired = 7;</code>
     */
    const OperationRetryRequired = 7;
}

