<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DssSignResult.proto

namespace Diadoc\Proto;

/**
 * Protobuf type <code>Diadoc.Proto.DssOperator</code>
 */
class DssOperator
{
    /**
     * Generated from protobuf enum <code>OperatorUnknown = 0;</code>
     */
    const OperatorUnknown = 0;
    /**
     * Generated from protobuf enum <code>Megafon = 1;</code>
     */
    const Megafon = 1;
    /**
     * Generated from protobuf enum <code>Kontur = 2;</code>
     */
    const Kontur = 2;
}

