<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DssSignRequest.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.DssSignFile</code>
 */
class DssSignFile extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Content_v3 Content = 1;</code>
     */
    private $Content = null;
    /**
     * Generated from protobuf field <code>string FileName = 2;</code>
     */
    private $FileName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\Content_v3 $Content
     *     @type string $FileName
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DssSignRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Content_v3 Content = 1;</code>
     * @return \Diadoc\Proto\Content_v3
     */
    public function getContent()
    {
        return $this->Content;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.Content_v3 Content = 1;</code>
     * @param \Diadoc\Proto\Content_v3 $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Proto\Content_v3::class);
        $this->Content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FileName = 2;</code>
     * @return string
     */
    public function getFileName()
    {
        return $this->FileName;
    }

    /**
     * Generated from protobuf field <code>string FileName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->FileName = $var;

        return $this;
    }

}

