<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DssSignResult.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.DssSignResult</code>
 */
class DssSignResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DssOperationStatus OperationStatus = 1;</code>
     */
    private $OperationStatus = 0;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DssFileSigningResult FileSigningResults = 2;</code>
     */
    private $FileSigningResults;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DssConfirmType ConfirmType = 3;</code>
     */
    private $ConfirmType = 0;
    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DssOperator Operator = 4;</code>
     */
    private $Operator = 0;
    /**
     * Generated from protobuf field <code>string PhoneLastNumbers = 5;</code>
     */
    private $PhoneLastNumbers = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $OperationStatus
     *     @type \Diadoc\Proto\DssFileSigningResult[]|\Google\Protobuf\Internal\RepeatedField $FileSigningResults
     *     @type int $ConfirmType
     *     @type int $Operator
     *     @type string $PhoneLastNumbers
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DssSignResult::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DssOperationStatus OperationStatus = 1;</code>
     * @return int
     */
    public function getOperationStatus()
    {
        return $this->OperationStatus;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DssOperationStatus OperationStatus = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOperationStatus($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\DssOperationStatus::class);
        $this->OperationStatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DssFileSigningResult FileSigningResults = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFileSigningResults()
    {
        return $this->FileSigningResults;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DssFileSigningResult FileSigningResults = 2;</code>
     * @param \Diadoc\Proto\DssFileSigningResult[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFileSigningResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DssFileSigningResult::class);
        $this->FileSigningResults = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DssConfirmType ConfirmType = 3;</code>
     * @return int
     */
    public function getConfirmType()
    {
        return $this->ConfirmType;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DssConfirmType ConfirmType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setConfirmType($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\DssConfirmType::class);
        $this->ConfirmType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DssOperator Operator = 4;</code>
     * @return int
     */
    public function getOperator()
    {
        return $this->Operator;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Proto.DssOperator Operator = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Proto\DssOperator::class);
        $this->Operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string PhoneLastNumbers = 5;</code>
     * @return string
     */
    public function getPhoneLastNumbers()
    {
        return $this->PhoneLastNumbers;
    }

    /**
     * Generated from protobuf field <code>string PhoneLastNumbers = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPhoneLastNumbers($var)
    {
        GPBUtil::checkString($var, True);
        $this->PhoneLastNumbers = $var;

        return $this;
    }

}

