<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DssSignRequest.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.DssSignRequest</code>
 */
class DssSignRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DssSignFile Files = 1;</code>
     */
    private $Files;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\DssSignFile[]|\Google\Protobuf\Internal\RepeatedField $Files
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DssSignRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DssSignFile Files = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFiles()
    {
        return $this->Files;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.DssSignFile Files = 1;</code>
     * @param \Diadoc\Proto\DssSignFile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\DssSignFile::class);
        $this->Files = $arr;

        return $this;
    }

}

