<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RoamingOperatorInformation.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>Diadoc.Proto.RoamingOperatorInformation</code>
 */
class RoamingOperatorInformation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.RoamingOperator RoamingOperators = 1;</code>
     */
    private $RoamingOperators;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Proto\RoamingOperator[] $RoamingOperators
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RoamingOperatorInformation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.RoamingOperator RoamingOperators = 1;</code>
     * @return RepeatedField<\Diadoc\Proto\RoamingOperator>
     */
    public function getRoamingOperators()
    {
        return $this->RoamingOperators;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.RoamingOperator RoamingOperators = 1;</code>
     * @param \Diadoc\Proto\RoamingOperator[] $var
     * @return $this
     */
    public function setRoamingOperators($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\RoamingOperator::class);
        $this->RoamingOperators = $arr;

        return $this;
    }

}

