<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RoamingOperatorInformation.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Proto.RoamingOperator</code>
 */
class RoamingOperator extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string FnsId = 1;</code>
     */
    private $FnsId = '';
    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    private $Name = '';
    /**
     * Generated from protobuf field <code>bool IsActive = 3;</code>
     */
    private $IsActive = false;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OperatorFeature Features = 4;</code>
     */
    private $Features;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $FnsId
     *     @type string $Name
     *     @type bool $IsActive
     *     @type \Diadoc\Proto\OperatorFeature[]|\Google\Protobuf\Internal\RepeatedField $Features
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RoamingOperatorInformation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string FnsId = 1;</code>
     * @return string
     */
    public function getFnsId()
    {
        return $this->FnsId;
    }

    /**
     * Generated from protobuf field <code>string FnsId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFnsId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FnsId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsActive = 3;</code>
     * @return bool
     */
    public function getIsActive()
    {
        return $this->IsActive;
    }

    /**
     * Generated from protobuf field <code>bool IsActive = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsActive($var)
    {
        GPBUtil::checkBool($var);
        $this->IsActive = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OperatorFeature Features = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFeatures()
    {
        return $this->Features;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Proto.OperatorFeature Features = 4;</code>
     * @param \Diadoc\Proto\OperatorFeature[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFeatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Proto\OperatorFeature::class);
        $this->Features = $arr;

        return $this;
    }

}

